// Language translations
const translations = {
    en: {
        title: "Will You Be My Valentine?",
        message: "Every moment with you makes my heart skip a beat...",
        yesBtn: "Yes, I'd love to! 💖",
        noBtn: "No, thanks",
        celebration: "Yay! 🎉",
        celebrationMessage: "You've made me the happiest person!",
        uploadPhoto: "Upload Photo",
        changePhoto: "Change Photo",
        selectTheme: "Select Theme",
        share: "Share",
        save: "Save",
        export: "Export",
        selectLanguage: "Language",
        animationPreset: "Animation",
        soundEnabled: "Sound",
        photoPlaceholder: "Add your photo here"
    },
    es: {
        title: "¿Quieres Ser Mi San Valentín?",
        message: "Cada momento contigo hace que mi corazón se acelere...",
        yesBtn: "¡Sí, me encantaría! 💖",
        noBtn: "No, gracias",
        celebration: "¡Yay! 🎉",
        celebrationMessage: "¡Me has hecho la persona más feliz!",
        uploadPhoto: "Subir Foto",
        changePhoto: "Cambiar Foto",
        selectTheme: "Seleccionar Tema",
        share: "Compartir",
        save: "Guardar",
        export: "Exportar",
        selectLanguage: "Idioma",
        animationPreset: "Animación",
        soundEnabled: "Sonido",
        photoPlaceholder: "Añade tu foto aquí"
    },
    fr: {
        title: "Veux-tu être mon Valentin?",
        message: "Chaque moment avec toi fait battre mon cœur...",
        yesBtn: "Oui, j'adorerais! 💖",
        noBtn: "Non, merci",
        celebration: "Yay! 🎉",
        celebrationMessage: "Tu m'as rendu la personne la plus heureuse!",
        uploadPhoto: "Télécharger Photo",
        changePhoto: "Changer Photo",
        selectTheme: "Sélectionner Thème",
        share: "Partager",
        save: "Enregistrer",
        export: "Exporter",
        selectLanguage: "Langue",
        animationPreset: "Animation",
        soundEnabled: "Son",
        photoPlaceholder: "Ajoutez votre photo ici"
    },
    de: {
        title: "Willst du mein Valentin sein?",
        message: "Jeder Moment mit dir lässt mein Herz höher schlagen...",
        yesBtn: "Ja, das würde ich lieben! 💖",
        noBtn: "Nein, danke",
        celebration: "Yay! 🎉",
        celebrationMessage: "Du hast mich zum glücklichsten Menschen gemacht!",
        uploadPhoto: "Foto hochladen",
        changePhoto: "Foto ändern",
        selectTheme: "Thema auswählen",
        share: "Teilen",
        save: "Speichern",
        export: "Exportieren",
        selectLanguage: "Sprache",
        animationPreset: "Animation",
        soundEnabled: "Ton",
        photoPlaceholder: "Fügen Sie Ihr Foto hier hinzu"
    },
    it: {
        title: "Vuoi essere il mio San Valentino?",
        message: "Ogni momento con te fa battere il mio cuore...",
        yesBtn: "Sì, mi piacerebbe! 💖",
        noBtn: "No, grazie",
        celebration: "Yay! 🎉",
        celebrationMessage: "Mi hai reso la persona più felice!",
        uploadPhoto: "Carica Foto",
        changePhoto: "Cambia Foto",
        selectTheme: "Seleziona Tema",
        share: "Condividi",
        save: "Salva",
        export: "Esporta",
        selectLanguage: "Lingua",
        animationPreset: "Animazione",
        soundEnabled: "Suono",
        photoPlaceholder: "Aggiungi la tua foto qui"
    },
    pt: {
        title: "Quer Ser Meu Valentim?",
        message: "Cada momento com você faz meu coração acelerar...",
        yesBtn: "Sim, eu adoraria! 💖",
        noBtn: "Não, obrigado",
        celebration: "Yay! 🎉",
        celebrationMessage: "Você me fez a pessoa mais feliz!",
        uploadPhoto: "Enviar Foto",
        changePhoto: "Alterar Foto",
        selectTheme: "Selecionar Tema",
        share: "Compartilhar",
        save: "Salvar",
        export: "Exportar",
        selectLanguage: "Idioma",
        animationPreset: "Animação",
        soundEnabled: "Som",
        photoPlaceholder: "Adicione sua foto aqui"
    },
    ja: {
        title: "バレンタインになってくれますか？",
        message: "あなたとのすべての瞬間が私の心を躍らせます...",
        yesBtn: "はい、喜んで！💖",
        noBtn: "いいえ、結構です",
        celebration: "やったー！🎉",
        celebrationMessage: "あなたは私を最も幸せな人にしてくれました！",
        uploadPhoto: "写真をアップロード",
        changePhoto: "写真を変更",
        selectTheme: "テーマを選択",
        share: "共有",
        save: "保存",
        export: "エクスポート",
        selectLanguage: "言語",
        animationPreset: "アニメーション",
        soundEnabled: "音",
        photoPlaceholder: "ここに写真を追加"
    },
    zh: {
        title: "你愿意做我的情人吗？",
        message: "和你在一起的每一刻都让我的心跳加速...",
        yesBtn: "是的，我愿意！💖",
        noBtn: "不，谢谢",
        celebration: "太好了！🎉",
        celebrationMessage: "你让我成为了最幸福的人！",
        uploadPhoto: "上传照片",
        changePhoto: "更改照片",
        selectTheme: "选择主题",
        share: "分享",
        save: "保存",
        export: "导出",
        selectLanguage: "语言",
        animationPreset: "动画",
        soundEnabled: "声音",
        photoPlaceholder: "在这里添加您的照片"
    }
};

